#!/bin/sh
# Starts rtorrent if it is not already running

FILE="$HOME/downloads/.session/rtorrent.lock"
SERVICE='rtorrent'
PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin

  if ps -u $LOGNAME u | grep -v grep | grep $SERVICE > /dev/null
  then
    echo "$SERVICE is running."
  else
    rm -f $FILE
    echo "$SERVICE is not running, starting $SERVICE" && /home/USERNAME-HERE/restartSeedbox
  fi
