#!/bin/sh
# By dannyti ---> https://github.com/dannyti/
#
#
######################################################################
#
#  Copyright (c) 2015 dannyti (https://github.com/dannyti/)
# Starts rtorrent if it is not already running

FILE="$HOME/downloads/.session/rtorrent.lock"
SERVICE='rtorrent'
PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin

  if pgrep -fx -u $LOGNAME $SERVICE > /dev/null
  then
    echo "$SERVICE is running."
  else
    rm -f $FILE
    echo "$SERVICE is not running, starting $SERVICE" && /home/$LOGNAME/restartSeedbox
  fi
